const iconNames = {
  eye: 'eye',
  eyeOff: 'eye-off',
  email: 'email',
  copyright: 'copyright',
  videoCall: 'Video-Call',
  leftArrow: 'arrow-left',
  cart: 'cart',
  menu: 'menu',
  verticalDots: 'dots-vertical',
  logout: 'logout',
  account: 'account',
  camera: 'camera',
  gallery: 'image',
  remove: 'delete',
  favorites: 'heart',
  favorites_outline:'heart-outline',
  home: 'home',
  star:'star',
  half_star:'star-half-full',
  star_outline:'star-outline',
  information:'information',
  notifications:'bell-circle',
  forward:'greater-than',
  language:'format-text',
  privacy:'security',
  theme:'white-balance-sunny',
  phone:'phone',
  check:"check",
  soundOn:'music',
  soundOff:'music-off',
  cancel:'window-close',
  right:"chevron-right",

  ionicons: {
    home: 'home',
    home_outline: 'home-outline',
    heart: 'heart-circle',
    heart_outline: 'heart-circle-outline',
    calender: 'calendar',
    calender_outline: 'calendar-outline',
    settings: 'settings',
    settings_outline: 'settings-outline',
    person:'person',
    back_arrow:'arrow-back',
    location:'location',
    location_outline:'location-outline',
    services:'receipt',
    services_outline:'receipt-outline',
    search:'search',
    close:'close'

    
  },
};

export { iconNames};
